# Generated by Django 4.2 on 2025-11-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('ARCHIVED', 'Archivado')], default='ACTIVE', max_length=10, verbose_name='Estado'),
        ),
    ]
